import { describe, expect, it } from "vitest"
import { BANKS, buildVietQr, cleanAmount, crc16, findBank, sanitizeMessage } from "./vietqr"

describe("crc16", () => {
  it("matches the CRC-16/CCITT-FALSE check value", () => {
    expect(crc16("123456789")).toBe("29B1")
  })
})

describe("buildVietQr", () => {
  // Reference payloads decoded from images generated by img.vietqr.io (fake account numbers).
  it("matches the official generator with amount and note", () => {
    expect(buildVietQr({ bin: "970436", account: "1234567890", amount: "150000", message: "Trả tiền ăn trưa" })).toBe(
      "00020101021238540010A00000072701240006970436011012345678900208QRIBFTTA530370454061500005802VN62200816Tra tien an trua630471F1",
    )
  })

  it("matches the official generator for a static code", () => {
    expect(buildVietQr({ bin: "970422", account: "0987654321", amount: "", message: "" })).toBe(
      "00020101021138540010A00000072701240006970422011009876543210208QRIBFTTA53037045802VN6304AF19",
    )
  })

  it("ignores spaces in the account and formatting in the amount", () => {
    const a = buildVietQr({ bin: "970436", account: "1234 5678 90", amount: "150.000", message: "" })
    const b = buildVietQr({ bin: "970436", account: "1234567890", amount: "150000", message: "" })
    expect(a).toBe(b)
  })

  it("returns nothing until bank and account are valid", () => {
    expect(buildVietQr({ bin: "", account: "123", amount: "", message: "" })).toBe("")
    expect(buildVietQr({ bin: "970436", account: "", amount: "", message: "" })).toBe("")
    expect(buildVietQr({ bin: "970436", account: "12345678901234567890", amount: "", message: "" })).toBe("")
  })
})

describe("helpers", () => {
  it("strips diacritics and symbols from the note", () => {
    expect(sanitizeMessage("  Đóng tiền   học — tháng 9! ")).toBe("Dong tien hoc thang 9")
    expect(sanitizeMessage("x".repeat(80))).toHaveLength(50)
  })

  it("cleans amounts", () => {
    expect(cleanAmount("1.500.000 ₫")).toBe("1500000")
    expect(cleanAmount("000")).toBe("")
  })

  it("ships a bank list with valid BINs", () => {
    expect(BANKS.length).toBeGreaterThan(50)
    expect(BANKS.every((b) => /^\d{6}$/.test(b.bin))).toBe(true)
    expect(findBank("970436")?.short).toBe("Vietcombank")
  })
})
